version: '2'
name: employee-layoffs

services:
  app:
    image: 'employee-layoffs:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app_employee_layoffs
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    container_name: db_employee_layoffs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_employee_layoffs
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - SPRING_RABBITMQ_HOST= rabbitmq_employee_layoffs
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest